<?php
    namespace Config;
/**
 * Generated by framework installer - Thu, 08 Feb 2018 19:37:11 +0100
*/
    class Config
    {
	const BASEDNAME	= '/dissertation';
	const DBHOST	= 'localhost';
	const DB	= 'dissertation';
	const DBUSER	= 'b5037590';
	const DBPW	= 'JIC16uao';
	const SITENAME	= 'dissertation';
	const SITEURL	= 'http://localhost.org//dissertation/';
	const SITENOREPLY	= 'noreply@localhost.org';
	const SYSADMIN	= 'M.Forbes1@ncl.ac.uk';
	const DBRX	= FALSE;
	const UPUBLIC	= TRUE;
	const UPRIVATE	= TRUE;
	const USEPHPM	= FALSE;

        public static function setup()
        {
            \Framework\Web\Web::getinstance()->addheader([
            'Date'			=> gmstrftime('%b %d %Y %H:%M:%S', time()),
            'Window-target'		=> '_top',	# deframes things
            'X-Frame-Options'	=> 'DENY',	# deframes things
            'Content-Language'	=> 'en',
            'Vary'			=> 'Accept-Encoding',
            ]);
        }
    }
?>